#!/bin/bash

# This test file will be executed against an auto-generated devcontainer.json that
# includes the 'goreg' Feature with no options.
#
# This is the AUTOGENERATED smoke test - it only verifies basic installation.
# For detailed functionality tests, see scenarios.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md

set -e

# Optional: Import test library bundled with the devcontainer CLI
# See https://github.com/devcontainers/cli/blob/HEAD/docs/features/test.md#dev-container-features-test-lib
# Provides the 'check' and 'reportResults' commands.
source dev-container-features-test-lib

# Smoke tests: Verify basic installation and command availability
# The 'check' command comes from the dev-container-features-test-lib.

check "goreg is installed" command -v goreg
check "goreg can display help" goreg --help

# Report results
# If any of the checks above exited with a non-zero exit code, the test will fail.
reportResults
